### ISSUE TITLE
Reorganize tests

### ISSUE THREAD

**Issue by zeridon** [fredhopper/hybris-connector#1]
The usual convention for java source is to have `src` and `test` directories in all modules.

Code need to be reorganized:

    fredhoppercore - no tests at all
    fredhoppersearch - testsrc should be renamed to tests
    fredhoppertemplate - testsrc should be renamed to tests

**Comment by Ciechorski** [comment]
Thanks for your input. 'testsrc' is actually a Hybris naming convention you will find throughout any Hybris project.

**Comment by pavelpenchev** [comment]
Thanks, as discussed fredhoppercore is a maven project while fredhoppersearch and fredhoppertemplate follow the Hybris code structure.

@zeridon can we close this one?

**Comment by zeridon** [comment]
If this is the case then yes
