### ISSUE TITLE
Review the updated Wiki pages

### ISSUE THREAD

**Issue by ikoevska** [fredhopper/hybris-connector#13]
I have done some work on the Wiki:

* Created a custom sidebar with the current resources.
* Archived the Connector Setup Step by Step (all of the information from there is in the readme).
* Archived the Installing the plug-in/Installing the extension page (all of the information there has been moved either to the readme or to the Overview page).
* Hid Page Directory from the navigation.
* Restructured and reworked [Overview](https://github.com/fredhopper/hybris-connector/wiki/Overview).
* Restructured and reworked [Generating and Publishing Data](https://github.com/fredhopper/hybris-connector/wiki/Generating-and-publishing-data).
* Restructured and reworked [Front-End Integration](https://github.com/fredhopper/hybris-connector/wiki/Front-end-integration).
* Restructured and reworked [Backoffice Management](https://github.com/fredhopper/hybris-connector/wiki/Backoffice-Management).

Since there is no way to submit PRs for wikis, please, check the updated content and let me know if there are any issues there. Also, do let me know if there is anything that seems like too much technical detail. Thanks.

**Comment by zeridon** [comment]
Looks good.

**Comment by jortegac** [comment]
Had a look. Things seem fine to me

**Comment by ikoevska** [comment]
Reviewed.
