### ISSUE TITLE
Change build system to be standard and not dependent on eclipse

### ISSUE THREAD

**Issue by zeridon** [fredhopper/hybris-connector#4]
As far as i can understand the project is expected to be compiled with Eclipse.

There is no portable/standardized way to compile it. It's preferable to have a standard build system e.g. Maven, ANT

**Comment by mau-fyayc** [comment]
@zeridon : Eclipse is not used for the compilation. Ant and Maven are.
This project cannot be used standalone and must be integrated in a SAP Hybris Platform as described in the installation procedure. As a build system it is used the standard SAP Hybris Ant build system.
That cannot be changed.
